/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SateliteClinic;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.Organization.Organization;
import Business.Organization.ProviderOrganization;
import Business.Useraccount.UserAccount;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class ClinicWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ClinicWorkArea
     */
    public ClinicWorkArea() {
        initComponents();
    }
    private JPanel p;
    private EcoSystem b;
    private UserAccount ua;
    private ClinicOrganization co;
    private Enterprise e;
    
    public ClinicWorkArea(JPanel p, EcoSystem b, Enterprise e, UserAccount ua, ClinicOrganization co) {
        initComponents();
        this.p = p;
        this.b = b;
        this.ua = ua;
        this.co = co;
        this.e = e;
        populatetbl2();
    }
    
    public void populatetbl1(){
       DefaultTableModel dtm= (DefaultTableModel)tbl1.getModel();
       dtm.setRowCount(0);
       
       for(Vaccine v : co.getVaccinedirectory().getVaccinedirectory()){
           Object row[] = new Object[2];
           row[0] = v;
           row[1] = v.getInventory();
           dtm.addRow(row);
       }
    }
    
    public void populatetbl2(){
       DefaultTableModel dtm= (DefaultTableModel)tbl2.getModel();
       dtm.setRowCount(0);
       
       for(Vaccine v : co.getPo().getVaccinedirectory().getVaccinedirectory()){
           Object row[] = new Object[2];
           row[0] = v;
           row[1] = v.getInventory();
           dtm.addRow(row);
       }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        deletevaccin = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vaccine Name", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        jLabel1.setText("From Provider");

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vaccine Name", "Amount"
            }
        ));
        jScrollPane2.setViewportView(tbl2);

        jLabel2.setText("Clinic");

        jLabel3.setText("Amount");

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Vaccine Name");

        deletevaccin.setText("Delete");
        deletevaccin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevaccinActionPerformed(evt);
            }
        });

        savebtn.setText("Save");
        savebtn.setEnabled(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        backbtn.setText("Logout");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t1)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletevaccin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(savebtn))))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn)
                    .addComponent(savebtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editbtn)
                    .addComponent(deletevaccin))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        Vaccine v = new Vaccine();
        Scanner sc1 = new Scanner(t2.getText());
        if(!t1.getText().isEmpty()&&sc1.hasNextInt()&&Integer.parseInt(t2.getText())>0){
            v.setInventory(Integer.parseInt(t2.getText()));
            v.setVaccinename(t1.getText());
            co.getVaccinedirectory().getVaccinedirectory().add(v);
            populatetbl1();
            DB4OUtil.getInstance().storeSystem(b);
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Inputs");
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0){
            Vaccine v= (Vaccine)tbl1.getValueAt(selectedrow,0);
            t1.setText(v.getVaccinename());
            t2.setText(String.valueOf(v.getInventory()));
            savebtn.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }

    }//GEN-LAST:event_editbtnActionPerformed

    private void deletevaccinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevaccinActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0){
            Vaccine v= (Vaccine)tbl1.getValueAt(selectedrow,0);
            co.getVaccinedirectory().getVaccinedirectory().remove(v);
            JOptionPane.showMessageDialog(null,"Deleted");
            populatetbl1();
            DB4OUtil.getInstance().storeSystem(b);
        }else{
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }
    }//GEN-LAST:event_deletevaccinActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0)
        {
            Vaccine v= (Vaccine)tbl1.getValueAt(selectedrow,0);
            Scanner sc1 = new Scanner(t2.getText());
            if(!t1.getText().isEmpty()&&sc1.hasNextInt()&&Integer.parseInt(t2.getText())>0){
                co.getVaccinedirectory().getVaccinedirectory().remove(v);
                v.setInventory(Integer.parseInt(t2.getText()));
                v.setVaccinename(t1.getText());
                co.getVaccinedirectory().getVaccinedirectory().add(v);
                JOptionPane.showMessageDialog(null,"Updated");
                savebtn.setEnabled(false);
                populatetbl1();
                DB4OUtil.getInstance().storeSystem(b);
            }else{
                JOptionPane.showMessageDialog(null,"Please Select Any Row");
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletevaccin;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
}
