/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Provider;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.Organization.Organization;
import Business.Organization.ProviderOrganization;
import Business.Role.Clinic;
import Business.Useraccount.UserAccount;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */

public class ProviderWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkArea
     */
    private JPanel p;
    private EcoSystem b;
    private UserAccount ua;
    private ProviderOrganization po;
    private Enterprise e;
    
    public ProviderWorkArea(JPanel p, EcoSystem b, Enterprise e, UserAccount ua, ProviderOrganization po) {
        initComponents();
        this.p = p;
        this.b = b;
        this.ua = ua;
        this.po = po;
        this.e = e;
        populatetbl2();
        populatetbl1();
        populatetbl3();
    }
    public void populatetbl1(){
       DefaultTableModel dtm= (DefaultTableModel)tbl1.getModel();
       dtm.setRowCount(0);
       
       for(Vaccine v : po.getVaccinedirectory().getVaccinedirectory()){
           Object row[] = new Object[2];
           row[0] = v;
           row[1] = v.getInventory();
           dtm.addRow(row);
       }
    }
    
    public void populatetbl2(){
        DefaultTableModel dtm= (DefaultTableModel)tbl2.getModel();
        dtm.setRowCount(0);
       
        for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
            if(o.getName().equals("Satelite Clinic Organization")){
                Object row[]= new Object[2];
                row[0] = o;
                row[1] = o.getOrganizationID();
                dtm.addRow(row);
            }
           
       }
    }
    
    public void populatetbl3(){
        DefaultTableModel dtm= (DefaultTableModel)tbl3.getModel();
        dtm.setRowCount(0);
       
        for(ClinicOrganization o : po.getClinic()){
            Object row[]= new Object[2];
                row[0] = o;
                row[1] = o.getOrganizationID();
                dtm.addRow(row);
            
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        addclinicbtn = new javax.swing.JButton();
        deleteclinic = new javax.swing.JButton();
        deletevaccin = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl3 = new javax.swing.JTable();

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vaccine Name", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tbl1);
        if (tbl1.getColumnModel().getColumnCount() > 0) {
            tbl1.getColumnModel().getColumn(1).setResizable(false);
            tbl1.getColumnModel().getColumn(1).setHeaderValue("Amount");
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Provider Work Area");

        backbtn.setText("Logout");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Vaccine Name");

        jLabel3.setText("Amount");

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Clinic Name", "Clinic ID"
            }
        ));
        jScrollPane2.setViewportView(tbl2);

        jLabel4.setText("Clinic Name");

        addclinicbtn.setText("Add");
        addclinicbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclinicbtnActionPerformed(evt);
            }
        });

        deleteclinic.setText("Delete");
        deleteclinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteclinicActionPerformed(evt);
            }
        });

        deletevaccin.setText("Delete");
        deletevaccin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevaccinActionPerformed(evt);
            }
        });

        savebtn.setText("Save");
        savebtn.setEnabled(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        tbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Clinic Name", "Clinic ID"
            }
        ));
        jScrollPane3.setViewportView(tbl3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(t2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletevaccin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(savebtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addclinicbtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(deleteclinic))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn)
                    .addComponent(savebtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editbtn)
                    .addComponent(deletevaccin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteclinic)
                    .addComponent(addclinicbtn))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        Vaccine v = new Vaccine();
        Scanner sc1 = new Scanner(t2.getText());
        if(!t1.getText().isEmpty()&&sc1.hasNextInt()&&Integer.parseInt(t2.getText())>0){
            v.setInventory(Integer.parseInt(t2.getText()));
            v.setVaccinename(t1.getText());
            po.getVaccinedirectory().getVaccinedirectory().add(v);
            populatetbl1();
            DB4OUtil.getInstance().storeSystem(b);
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Inputs");
        }
        
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0){
            Vaccine v= (Vaccine)tbl1.getValueAt(selectedrow,0);
            t1.setText(v.getVaccinename());
            t2.setText(String.valueOf(v.getInventory()));
            savebtn.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null,"Please Select Any Row");
            }
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void deletevaccinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevaccinActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0){
            Vaccine v= (Vaccine)tbl1.getValueAt(selectedrow,0);
            po.getVaccinedirectory().getVaccinedirectory().remove(v);
            JOptionPane.showMessageDialog(null,"Deleted");
            populatetbl1();
            DB4OUtil.getInstance().storeSystem(b);
        }else{
                JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }
    }//GEN-LAST:event_deletevaccinActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0)
        {
            Vaccine v= (Vaccine)tbl1.getValueAt(selectedrow,0);
            Scanner sc1 = new Scanner(t2.getText());
            if(!t1.getText().isEmpty()&&sc1.hasNextInt()&&Integer.parseInt(t2.getText())>0){
                po.getVaccinedirectory().getVaccinedirectory().remove(v);
                v.setInventory(Integer.parseInt(t2.getText()));
                v.setVaccinename(t1.getText());
                po.getVaccinedirectory().getVaccinedirectory().add(v);
                JOptionPane.showMessageDialog(null,"Updated");
                savebtn.setEnabled(false);
                populatetbl1();
                DB4OUtil.getInstance().storeSystem(b);
            }else{
                JOptionPane.showMessageDialog(null,"Please Select Any Row");
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void addclinicbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclinicbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl2.getSelectedRow();
        if(selectedrow >=0)
        {
            ClinicOrganization co= (ClinicOrganization)tbl2.getValueAt(selectedrow,0);
            po.getClinic().add(co);
            co.setPo(po);
            populatetbl3();
            DB4OUtil.getInstance().storeSystem(b);
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Inputs");
        }
    }//GEN-LAST:event_addclinicbtnActionPerformed

    private void deleteclinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteclinicActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl3.getSelectedRow();
        if(selectedrow >=0){
            ClinicOrganization c= (ClinicOrganization)tbl3.getValueAt(selectedrow,0);
            po.getClinic().remove(c);
            JOptionPane.showMessageDialog(null,"Deleted");
            populatetbl3();
            DB4OUtil.getInstance().storeSystem(b);
        }else{
                JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }
    }//GEN-LAST:event_deleteclinicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton addclinicbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deleteclinic;
    private javax.swing.JButton deletevaccin;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTable tbl3;
    // End of variables declaration//GEN-END:variables
}
