/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SupplierAdmin;

import Interface.ProviderAdmin.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ruby
 */
public class SupplierManage extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdminManage
     */
    private JPanel p;
    private EcoSystem b;
    private UserAccount ua;
    private Organization o;
    private Enterprise e;
    
    
    public SupplierManage(JPanel p, EcoSystem b, UserAccount ua, Organization o, Enterprise e) {
        initComponents();
        this.p = p;
        this.b = b;
        this.ua = ua;
        this.o = o;
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personbtn = new javax.swing.JButton();
        organizationbtn = new javax.swing.JButton();
        userbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        personbtn.setText("Manage Person");
        personbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personbtnActionPerformed(evt);
            }
        });

        organizationbtn.setText("Manage Organization");
        organizationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationbtnActionPerformed(evt);
            }
        });

        userbtn.setText("Manage UserAccount");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });

        backbtn.setText("Logout");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Supplier Admin Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(organizationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(organizationbtn)
                .addGap(18, 18, 18)
                .addComponent(personbtn)
                .addGap(18, 18, 18)
                .addComponent(userbtn)
                .addGap(68, 68, 68)
                .addComponent(backbtn)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void personbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personbtnActionPerformed
        // TODO add your handling code here:
        SupplierPersonManage panel = new SupplierPersonManage(b,p,ua,o,e);
        p.add("ProviderPersonManage",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_personbtnActionPerformed

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        SupplierUserAccountManage panel = new SupplierUserAccountManage(b,p,ua,o,e);
        p.add("ProviderUserAccountManage",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_userbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed

    private void organizationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationbtnActionPerformed
        // TODO add your handling code here:
        SupplierOrganizationManage panel = new SupplierOrganizationManage(b,p,ua,o,e);
        p.add("ProviderOrganizationManage",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_organizationbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton organizationbtn;
    private javax.swing.JButton personbtn;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
}
