/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user.admin;

import business.Business;
import business.Order;
import business.PersonAndAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class AboveTarget extends javax.swing.JPanel {

    /** Creates new form AboveTagert */
    private Business b;
    private JPanel pp;
    private PersonAndAccount pa;
    AboveTarget(Business b, JPanel pp, PersonAndAccount pa) {
        initComponents();
        this.b = b;
        this.pp = pp;
        this.pa = pa;
//To change body of generated methods, choose Tools | Templates.
        DefaultTableModel dtm= (DefaultTableModel)tbl.getModel();
        dtm.setRowCount(0);
        Object row[]= new Object[1];
        for(int i=0;i<AboveTargets().size();i++){
            row[0]=AboveTargets().get(i);
            dtm.addRow(row);
        }
    }
    
    public ArrayList<String> AboveTargets(){
        ArrayList<String> a = new ArrayList();
        for(int i=0; i<pa.getRolemanage().getSalesman().size(); i++){
            Boolean test = null;
            ArrayList<Order> o = new ArrayList<Order>();
            for(int j=0; j<b.getOrderlist().getOrder().size(); j++){
                if(b.getOrderlist().getOrder().get(j).getSalesmanname().equals(pa.getRolemanage().getSalesman().get(i).getFullname())){
                    o.add(b.getOrderlist().getOrder().get(j));
                }
            }
            for(int j=0;j<o.size();j++){
                if(o.get(j).getActualprice()-o.get(j).getTargetprice()<0){
                    test = false;
                    break;
                }
            }
            if(test == null){
                a.add(pa.getRolemanage().getSalesman().get(i).getFullname());
            }
        }
        return a;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Above Target Sales");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name List"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

}
