/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.admin;

import business.Business;
import business.PersonAndAccount;
import business.Rank;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class BelowTarget extends javax.swing.JPanel {

    /**
     * Creates new form BelowTarget
     */
    private Business b;
    private JPanel pp;
    private PersonAndAccount pa;
    BelowTarget(Business b, JPanel pp, PersonAndAccount pa) {
        initComponents();
        this.b = b;
        this.pp = pp;
        this.pa = pa;
//To change body of generated methods, choose Tools | Templates.
         ArrayList<String> a = new ArrayList<String>();
            for(int i=0; i<RankByGap("Education").size();i++){
                if(RankByGap("Education").get(i).getIncome()<0){
                    a.add(RankByGap("Education").get(i).getName());
                }
            }
            for(int i=0; i<RankByGap("Financial").size();i++){
                if(RankByGap("Financial").get(i).getIncome()<0){
                    a.add(RankByGap("Financial").get(i).getName());
                }
            }
        DefaultTableModel dtm= (DefaultTableModel)tbl.getModel();
        dtm.setRowCount(0);
        Object row[]= new Object[1];
        for(int i=0; i<a.size();i++){
            row[0] = a.get(i);
            dtm.addRow(row);
        }
    }
    
    public ArrayList<Rank> RankByGap(String m){
        ArrayList<Rank> r = new ArrayList<Rank>();
        for(int i=0; i<pa.getRolemanage().getSalesman().size(); i++){
            if(pa.getRolemanage().getSalesman().get(i).getMarketname().equals(m)){
                Rank rk = new Rank();
                rk.setName(pa.getRolemanage().getSalesman().get(i).getFullname());
                rk.setIncome(GapByPerson(pa.getRolemanage().getSalesman().get(i).getFullname()));
                r.add(rk);
            }
        }
        Rank rk = new Rank();
        for(int i=0; i< r.size()-1;i++){
            for(int j=0; j<r.size()-1-i;j++){
                if(r.get(j).getIncome()<r.get(j+1).getIncome()){
                    rk.setIncome(r.get(j).getIncome());
                    rk.setName(r.get(j).getName());
                    r.get(j).setIncome(r.get(j+1).getIncome());
                    r.get(j).setName(r.get(j+1).getName());
                    r.get(j+1).setIncome(rk.getIncome());
                    r.get(j+1).setName(rk.getName());
                }
            }
        }
        
        return r;
    }
    public Double GapByPerson(String sm){
        double tr = 0;
        for(int i=0; i<b.getOrderlist().getOrder().size(); i++){
            if(b.getOrderlist().getOrder().get(i).getSalesmanname().equals(sm)){
                tr = tr + (b.getOrderlist().getOrder().get(i).getActualprice()-b.getOrderlist().getOrder().get(i).getTargetprice())*(double)b.getOrderlist().getOrder().get(i).getQuantity();
            }
        }
        return tr;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Below Target");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name List"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
