/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.admin;

import business.Admin;
import business.Business;
import business.Person;
import business.RoleManage;
import business.PersonAndAccount;
import business.Salesman;
import business.Supplier;
import business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class PersonManage extends javax.swing.JPanel {

    /**
     * Creates new form PersonManage
     */
    private Business b;
    private JPanel p;
    private PersonAndAccount pa;
    
    PersonManage(Business b, JPanel p, PersonAndAccount pa) {
         //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.b = b;
        this.p = p;
        this.pa = pa;
        populatetbl();
    }
    
    public void populatetbl(){
        DefaultTableModel dtm= (DefaultTableModel)tbl.getModel();
        dtm.setRowCount(0);
        for(Person ps: pa.getPersondirectory().getPerson()){
            Object row[]= new Object[2];
            row[0] = ps;
            ArrayList<String> psus = new ArrayList();
            for(int i=0; i<pa.getUseraccountdirectory().getUseraccount().size(); i++){
                if(pa.getUseraccountdirectory().getUseraccount().get(i).getFullname().equals(ps.getFullname())){
                    psus.add(pa.getUseraccountdirectory().getUseraccount().get(i).getUsername());
                }
            }
            String adusn = String.join(",",psus);
            row[1] = adusn;
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        createbtn = new javax.swing.JButton();
        adminbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        salesmanbtn = new javax.swing.JButton();
        supplierbtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Manage Person");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Full Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
        }

        createbtn.setText("Create");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });

        adminbtn.setText("Edit Admin");
        adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        salesmanbtn.setText("Edit Salesman");
        salesmanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesmanbtnActionPerformed(evt);
            }
        });

        supplierbtn.setText("Edit Supplier");
        supplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backbtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createbtn)
                                .addGap(18, 18, 18)
                                .addComponent(deletebtn))
                            .addComponent(adminbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supplierbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesmanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createbtn)
                            .addComponent(deletebtn))
                        .addGap(18, 18, 18)
                        .addComponent(adminbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salesmanbtn)
                        .addGap(18, 18, 18)
                        .addComponent(supplierbtn)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl.getSelectedRow();
        if(selectedrow >=0)
        {
            Person ps= (Person)tbl.getValueAt(selectedrow,0);
            ArrayList<UserAccount> countertargets = new ArrayList();
            for(int i=0; i<pa.getUseraccountdirectory().getUseraccount().size();i++){
                if(!ps.getFullname().equals(pa.getUseraccountdirectory().getUseraccount().get(i).getFullname())){
                    countertargets.add(pa.getUseraccountdirectory().getUseraccount().get(i));
                }
            }
            pa.getUseraccountdirectory().getUseraccount().clear();
            for(int i=0;i<countertargets.size();i++){
                 pa.getUseraccountdirectory().getUseraccount().add(countertargets.get(i));
            }
            if(ps.getPersonrole().equals("Admin")){
                for(int i=0;i<pa.getRolemanage().getAdmin().size();i++){
                    if(pa.getRolemanage().getAdmin().get(i).getFullname().equals(ps.getFullname())){
                        pa.getRolemanage().getAdmin().remove(pa.getRolemanage().getAdmin().get(i));
                        break;
                    }
                }
            }
            if(ps.getPersonrole().equals("Supplier")){
                for(int i=0;i<pa.getRolemanage().getSupplier().size();i++){
                    if(pa.getRolemanage().getSupplier().get(i).getSuppliername().equals(ps.getFullname())){
                        pa.getRolemanage().getSupplier().remove(pa.getRolemanage().getSupplier().get(i));
                        break;
                    }
                }
            }
            if(ps.getPersonrole().equals("Salesman")){
                for(int i=0;i<pa.getRolemanage().getSalesman().size();i++){
                    if(pa.getRolemanage().getSalesman().get(i).getFullname().equals(ps.getFullname())){
                        pa.getRolemanage().getSalesman().remove(pa.getRolemanage().getSalesman().get(i));
                        break;
                    }
                }
            }
            pa.getPersondirectory().deletePerson(ps);
            JOptionPane.showMessageDialog(null,"Deleted");
            populatetbl();
        }
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        CreatePerson panel = new CreatePerson(b,p,pa);
        p.add("createperson",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_createbtnActionPerformed

    private void adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnActionPerformed
        // TODO add your handling code here:
        AdminEdit panel = new AdminEdit(b,p,pa);
        p.add("updateperson",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
        
    }//GEN-LAST:event_adminbtnActionPerformed

    private void salesmanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesmanbtnActionPerformed
        // TODO add your handling code here:
        SalesmanManage panel = new SalesmanManage(b,p,pa);
        p.add("salesmanmanage",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_salesmanbtnActionPerformed

    private void supplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierbtnActionPerformed
        // TODO add your handling code here:
        SupplierManage panel = new SupplierManage(b,p,pa);
        p.add("updateperson",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_supplierbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton createbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salesmanbtn;
    private javax.swing.JButton supplierbtn;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
