/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.admin;

import business.Business;
import business.PersonAndAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class RevenueByMarket extends javax.swing.JPanel {

    /**
     * Creates new form RevenueByMarket
     */
    private Business b;
    private JPanel pp;
    private PersonAndAccount pa;
    
    RevenueByMarket(Business b, JPanel pp, PersonAndAccount pa) {
         //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.b = b;
        this.pp = pp;
        this.pa = pa;
        populatetbl1();
    }
    public void populatetbl1(){
        DefaultTableModel dtm= (DefaultTableModel)tbl1.getModel();
        dtm.setRowCount(0);
        Object row[]= new Object[3];
        row[0] = "Education";
        row[1] = RevenueByMarket("Education");
        row[2] = GapByMarket("Education");
        dtm.addRow(row);
        Object row2[]= new Object[3];
        row2[0] = "Financial";
        row2[1] = RevenueByMarket("Financial");
        row2[2] = GapByMarket("Financial");
        dtm.addRow(row2);
    }
    public Double RevenueByMarket(String m){
        double tr = 0;
        for(int i=0; i<b.getOrderlist().getOrder().size(); i++){
            if(b.getOrderlist().getOrder().get(i).getMarketname().equals(m)){
                tr = tr + b.getOrderlist().getOrder().get(i).getActualprice()*(double)b.getOrderlist().getOrder().get(i).getQuantity();
            }
        }
        return tr;
    }
    public Double GapByMarket(String m){
        double tr = 0;
        for(int i=0; i<b.getOrderlist().getOrder().size(); i++){
            if(b.getOrderlist().getOrder().get(i).getMarketname().equals(m)){
                tr = tr + (b.getOrderlist().getOrder().get(i).getActualprice()-b.getOrderlist().getOrder().get(i).getTargetprice())*(double)b.getOrderlist().getOrder().get(i).getQuantity();
            }
        }
        return tr;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Revenue By Market");

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market", "Revenue", "Gap"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl1;
    // End of variables declaration//GEN-END:variables
}
