/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.admin;

import business.Business;
import business.Order;
import business.PersonAndAccount;
import business.RankProduct;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class TopProducts extends javax.swing.JPanel {

    /**
     * Creates new form TopProducts
     */
    private Business b;
    private JPanel pp;
    private PersonAndAccount pa;
    TopProducts(Business b, JPanel pp, PersonAndAccount pa) {
        initComponents();
        this.b = b;
        this.pp = pp;
        this.pa = pa;
        populatetbl4();
    }
    
    public void populatetbl4(){
        DefaultTableModel dtm= (DefaultTableModel)tbl4.getModel();
        dtm.setRowCount(0);
        ArrayList<RankProduct> rp = new ArrayList<RankProduct>();
        for(int i=0; i<3;i++){
            rp.add(RankByProduct().get(i));
        }
        for(int i=0; i<rp.size();i++){
            Object row[] = new Object[3];
            row[0] = rp.get(i).getProductid();
            row[1] = rp.get(i).getProductname();
            row[2] = rp.get(i).getIncome();
            dtm.addRow(row);
        }
    }
    
    public ArrayList<RankProduct> RankByProduct(){
        ArrayList<RankProduct> r = new ArrayList<RankProduct>();
        for(int i=0; i<b.getProductdirectory().getproduct().size();i++){
            ArrayList<Order> o = new ArrayList<Order>();
            for(int j=0; j<b.getOrderlist().getOrder().size(); j++){
                if(b.getOrderlist().getOrder().get(j).getProductid()==b.getProductdirectory().getproduct().get(i).getProductid()){
                    o.add(b.getOrderlist().getOrder().get(j));
                }
            }
            Boolean test = null;
            for(int j=0;j<o.size();j++){
                if(o.get(j).getActualprice()-o.get(j).getTargetprice()<0){
                    test = false;
                    break;
                }
            }
            if(test == null){
                RankProduct rp = new RankProduct();
                rp.setIncome(GapByProduct(b.getProductdirectory().getproduct().get(i).getProductid()));
                rp.setProductid(b.getProductdirectory().getproduct().get(i).getProductid());
                rp.setProductname(b.getProductdirectory().getproduct().get(i).getProductname());
                r.add(rp);
            }
        }
        RankProduct rk = new RankProduct();
        for(int i=0; i< r.size()-1;i++){
            for(int j=0; j<r.size()-1-i;j++){
                if(r.get(j).getIncome()<r.get(j+1).getIncome()){
                    rk.setIncome(r.get(j).getIncome());
                    rk.setProductid(r.get(j).getProductid());
                    rk.setProductname(r.get(j).getProductname());
                    r.get(j).setIncome(r.get(j+1).getIncome());
                    r.get(j).setProductid(r.get(j+1).getProductid());
                    r.get(j).setProductname(r.get(j+1).getProductname());
                    r.get(j+1).setIncome(rk.getIncome());
                    r.get(j+1).setProductname(rk.getProductname());
                    r.get(j+1).setProductid(rk.getProductid());
                }
            }
        }
        return r;
    }
    
    public Double GapByProduct(int a){
        double tr = 0;
        for(int i=0; i<b.getOrderlist().getOrder().size(); i++){
            if(b.getOrderlist().getOrder().get(i).getProductid()==a){
                tr = tr + (b.getOrderlist().getOrder().get(i).getActualprice()-b.getOrderlist().getOrder().get(i).getTargetprice())*(double)b.getOrderlist().getOrder().get(i).getQuantity();
            }
        }
        return tr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl4 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Top 3 Products");

        tbl4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Gap"
            }
        ));
        jScrollPane6.setViewportView(tbl4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tbl4;
    // End of variables declaration//GEN-END:variables
}
