/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.airliner;

import business.AirlinerDirectory;
import business.Flight;
import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ruby
 */
public class AirlinerView extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerView
     */
    private JPanel p;
    private Flight f;
    private AirlinerDirectory a;

    public AirlinerView(JPanel p, Flight f, AirlinerDirectory a) {
        initComponents();
        this.f = f;
        this.p = p;
        this.a = a;
        details();
        
    }

    
    private void details(){
        t1.setText(String.valueOf(f.getFlightid()));
        t2.setText(f.getDepart());
        t3.setText(f.getArrive());
        t4.setText(f.getFrom());
        t5.setText(f.getTo());
        t6.setText(f.getDate());
        t7.setText(f.getCompany());
        t8.setText(f.getModel());
        t9.setText(String.valueOf(f.getMadeyear()));
        t10.setText(String.valueOf(f.getSeatprice())); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();

        t2.setEnabled(false);

        t3.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("View Flight");

        jLabel7.setText("Company");

        jLabel8.setText("Model");

        jLabel9.setText("Made Year");

        jLabel10.setText("Seats Average Price");

        t7.setEnabled(false);

        t8.setEnabled(false);

        t10.setEnabled(false);

        t9.setEnabled(false);

        t4.setEnabled(false);

        jLabel2.setText("Flight Number");

        t5.setEnabled(false);

        jLabel3.setText("Departure Time");

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Arrival Time");

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Departure City");

        jLabel6.setText("Arrival City");

        t1.setEnabled(false);

        savebtn.setText("Save");
        savebtn.setEnabled(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Flight Date");

        t6.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backbtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updatebtn)
                                .addGap(18, 18, 18)
                                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn)
                    .addComponent(savebtn))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        updatebtn.setEnabled(false);
        savebtn.setEnabled(true);
        t1.setEnabled(true);
        t2.setEnabled(true);
        t3.setEnabled(true);
        t4.setEnabled(true);
        t5.setEnabled(true);
        t6.setEnabled(true);
        t7.setEnabled(true);
        t8.setEnabled(true);
        t9.setEnabled(true);
        t10.setEnabled(true);   
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        Scanner sc1 = new Scanner(t1.getText());
        Date sc2 = null;
        Date sc3 = null;
        Date sc6 = null;
        Scanner sc9 = new Scanner(t9.getText());
        Scanner sc10 = new Scanner(t10.getText());
        Boolean e1 = null;
        Boolean e2 = null;
        Boolean e3 = null;
        Boolean e4 = null;
        Boolean e5 = null;
        Boolean e6 = null;
        Boolean e7 = null;
        Boolean e8 = null;
        Boolean e9 = null;
        Boolean e10 = null;
        if(!sc1.hasNextInt()){
            JOptionPane.showMessageDialog(null,"Invalid Flight ID");
            e1=false;
        }else{e1=true;}
        
        if(!t2.getText().isEmpty()){
            try {
                    DateFormat formatter = new SimpleDateFormat("HH:mm");
                    formatter.setLenient(false);
                    sc2 = formatter.parse(t2.getText());
                } catch (ParseException e) { e.printStackTrace();}
            if(sc2 == null){
                JOptionPane.showMessageDialog(null,"Invalid Time");
                e2= false;
            }else{e2=true;}
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Time");
            e2= false;
        }
        
        if(!t3.getText().isEmpty()){
            try {
                    DateFormat formatter = new SimpleDateFormat("HH:mm");
                    formatter.setLenient(false);
                    sc3 = formatter.parse(t3.getText());
                } catch (ParseException e) {e.printStackTrace();}
            if(sc3 == null){
                JOptionPane.showMessageDialog(null,"Invalid Time");
                e3= false;
            }else{e3=true;}
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Time");
            e3= false;
        }
        
        if(t4.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Departure City Required");
            e4= false;
        }else{e4=true;}
        
        if(t5.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Arrival City Required");
            e5= false;
        }else{e5=true;}
        
        if(!t6.getText().isEmpty()){
            try {
                    DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                    formatter.setLenient(false);
                    sc6 = formatter.parse(t6.getText());
                } catch (ParseException e) {e.printStackTrace();}
            if(sc6 == null){
                JOptionPane.showMessageDialog(null,"Invalid Date");
                e6= false;
            }else{e6=true;}
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Date");
            e6= false;
        }
        
        if(t7.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Company Required");
            e7= false;
        }else{e7=true;}
        
        if(t8.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Plane Model Required");
            e8= false;
        }else{e8=true;}
        
        if(!sc9.hasNextInt()){
            JOptionPane.showMessageDialog(null,"Invalid Year");
            e9=false;
        }else{
            if (Integer.parseInt(t9.getText())<=1990 || Integer.parseInt(t9.getText())>2017) {
            JOptionPane.showMessageDialog(null,"Invalid Year");
            e9=false;
            }else{e9=true;}
        }
        
        if(!sc10.hasNextDouble()){
            JOptionPane.showMessageDialog(null,"Invalid Price");
            e10=false;
        }else{e10=true;}
        
         
        
        
        if(e1&&e2&&e3&&e4&&e5&&e6&&e7&&e8&&e9&&e10){
            a.deleteFlights(f);
            int fn = Integer.parseInt(t1.getText());
            String dt = t2.getText();
            String at = t3.getText();
            String dc = t4.getText();
            String ac = t5.getText();
            String fd = t6.getText();
            String md = t8.getText();
            int my = Integer.parseInt(t9.getText());
            double sp = Double.parseDouble(t10.getText());
            String cp = t7.getText();
            
            Flight f = a.addFlight();
            f.setFlightid(fn);
            f.setDepart(dt);
            f.setArrive(at);
            f.setFrom(dc);
            f.setTo(ac);
            f.setDate(fd);
            f.setModel(md);
            f.setMadeyear(my);
            f.setSeatprice(sp);
            f.setCompany(cp);
            
            try{   
                BufferedWriter fw = new BufferedWriter(new FileWriter("airliner.txt"));
                for(Flight line : a.getAirliner()){
                    String[] a = new String[10];
                    a[0] = String.valueOf(line.getFlightid());
                    a[1] = line.getCompany();
                    a[2] = line.getDepart();
                    a[3] = line.getArrive();
                    a[4] = line.getFrom();
                    a[5] = line.getTo();
                    a[6] = line.getDate();
                    a[7] = line.getModel();
                    a[8] = String.valueOf(line.getMadeyear());
                    a[9] = String.valueOf(line.getSeatprice());
                    String thisline=Arrays.toString(a);
                    fw.write(thisline.replace("[", "").replace("]", "").replace(", ",","));
                    fw.newLine();
                }     
                fw.close();    
            }catch(Exception e){System.out.println(e);}    
            System.out.println("Success...");
            
            JOptionPane.showMessageDialog(null,"Updated");
            updatebtn.setEnabled(true);
            savebtn.setEnabled(false);
            t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);
            t5.setEnabled(false);
            t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);
            t9.setEnabled(false);
            t10.setEnabled(false);
        }
    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
