/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import user.airliner.AirlinerManagement;
import business.AirlinerDirectory;
import business.CustomerDirectory;
import business.Flight;
import business.Person;
import business.Reservation;
import business.ReservationDirectory;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import user.customer.CustomerManage;
import user.travelagency.AgencyManagement;
import user.customer.CustomerSearch;
/**
 *
 * @author Ruby
 */
public class Main extends javax.swing.JFrame {
    private AirlinerDirectory a;
    private CustomerDirectory c;
    private ReservationDirectory r;
    
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.a = new AirlinerDirectory();
        this.c = new CustomerDirectory(); 
        this.r = new ReservationDirectory();
        
        String thisLine = null;
        try {
                BufferedReader br = new BufferedReader(new FileReader("airliner.txt"));
                while ((thisLine = br.readLine()) != null) {
                    System.out.println(thisLine);
                    Flight f  =a.addFlight();
                    String[] a = thisLine.split(",");
                    f.setFlightid(Integer.parseInt(a[0]));
                    f.setCompany(a[1]);
                    f.setDepart(a[2]);
                    f.setArrive(a[3]);
                    f.setFrom(a[4]);
                    f.setTo(a[5]);
                    f.setDate(a[6]);
                    f.setModel(a[7]);
                    f.setMadeyear(Integer.parseInt(a[8]));
                    f.setSeatprice(Double.parseDouble(a[9]));
                }       
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        try {
                BufferedReader br = new BufferedReader(new FileReader("customer.txt"));
                while ((thisLine = br.readLine()) != null) {
                    System.out.println(thisLine);
                    Person p  = c.addPerson();
                    String[] a = thisLine.split(",");
                    p.setFirstname(a[0]);
                    p.setLastname(a[1]);
                    p.setEmail(a[2]);
                    p.setPhonenumber(Long.parseLong(a[3]));
                    p.setIdnum(Integer.parseInt(a[4]));
                }       
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        try {
                BufferedReader br = new BufferedReader(new FileReader("reservation.txt"));
                while ((thisLine = br.readLine()) != null) {
                    System.out.println(thisLine);
                    Reservation re  = r.addReservation();
                    String[] a = thisLine.split(",");
                    re.setReservationcode(Integer.parseInt(a[0]));
                    re.setFirstname(a[1]);
                    re.setLastname(a[2]);
                    re.setSeat(a[3]);
                    re.setDate(Long.parseLong(a[4]));
                    re.setFlightnumber(Integer.parseInt(a[5]));
                    re.setIdnum(Integer.parseInt(a[6]));
                    re.setFinalprice(Double.parseDouble(a[7]));
                }       
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        airlinerbtn = new javax.swing.JButton();
        customerbtn = new javax.swing.JButton();
        agencybtn = new javax.swing.JButton();
        p = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        airlinerbtn.setText("Airliner");
        airlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerbtnActionPerformed(evt);
            }
        });

        customerbtn.setText("Customer");
        customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerbtnActionPerformed(evt);
            }
        });

        agencybtn.setText("Agency");
        agencybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agencybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(customerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agencybtn, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(airlinerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(airlinerbtn)
                .addGap(87, 87, 87)
                .addComponent(agencybtn)
                .addGap(91, 91, 91)
                .addComponent(customerbtn)
                .addGap(318, 318, 318))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        p.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(p);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void airlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerbtnActionPerformed
        // TODO add your handling code here:
        AirlinerManagement panel = new AirlinerManagement(p,a);
        p.add("airlinermanagement",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_airlinerbtnActionPerformed

    private void customerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerbtnActionPerformed
        // TODO add your handling code here:
        CustomerManage panel = new CustomerManage(p,a,c,r);
        p.add("customermanage",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_customerbtnActionPerformed

    private void agencybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agencybtnActionPerformed
        // TODO add your handling code here:
        AgencyManagement panel = new AgencyManagement(p,a,r,c);
        p.add("agencymanagement",panel);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.next(p);
    }//GEN-LAST:event_agencybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agencybtn;
    private javax.swing.JButton airlinerbtn;
    private javax.swing.JButton customerbtn;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel p;
    // End of variables declaration//GEN-END:variables
}
