/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.History;
import Profile.PlaneInfo;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ruby
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPanel
     */
    private History ht;
    public EditPanel(History ht) {
        initComponents();
        this.ht=ht;
        populatetle();
         
    }
    
    public void populatetle(){
        DefaultTableModel dtm= (DefaultTableModel)tbl.getModel();
        dtm.setRowCount(0);
        
        for(PlaneInfo pi : ht.getHistory())
        {
            Object row[]= new Object[2];
            row[0] =pi;
            row[1] =formattime(pi.getUpdate());
            dtm.addRow(row);
        }
    }
    
    private String formattime(long update){
        Date dNow = new Date(update);
        SimpleDateFormat ft = 
        new SimpleDateFormat ("yyyy.MM.dd hh:mm");
        return ft.format(dNow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        editbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Edit Plane Information");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Plane ID", "Update Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
        }

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("Save Changes");
        updatebtn.setEnabled(false);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete Row");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Plane ID");

        jLabel3.setText("Availability");

        cb1.setText("Yes");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setText("No");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Manufacturer");

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select a Manufacturer--", "Boeing", "Airbus", "Bombardier", "Embraer", " ", " " }));

        jLabel5.setText("Year Made");

        jLabel6.setText("Total Seats");

        jLabel7.setText("Airliner");

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select an Airliner--", "Qatar Airways", "Singapore Airlines", "ANA All Nippon Airways", "Emirates", "Cathay Pacific", "EVA Air", "Lufthansa", "Etihad Airways", "Hainan Airlines", "Garuda Indonesia" }));

        jLabel8.setText("Model");

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select a Model--", "727", "737", "747", "757", "777", "787", "380" }));

        jLabel9.setText("Airport");

        jLabel10.setText("Maintainence Expire Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(deletebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(t5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb1)
                                .addGap(79, 79, 79)
                                .addComponent(cb2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t1)
                                .addComponent(c1, 0, 321, Short.MAX_VALUE)
                                .addComponent(t2)
                                .addComponent(t3)
                                .addComponent(c2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t4)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(deletebtn)
                        .addGap(69, 69, 69)
                        .addComponent(updatebtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb1)
                    .addComponent(cb2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        
        
        int selectedrow= tbl.getSelectedRow();
        if(selectedrow >=0)
        {
            updatebtn.setEnabled(true);
            tbl.setEnabled(false);
            deletebtn.setEnabled(false);
            editbtn.setEnabled(false);
            PlaneInfo pi= (PlaneInfo)tbl.getValueAt(selectedrow,0);
            t1.setText(String.valueOf(pi.getId()));
            t2.setText(String.valueOf(pi.getMadeyear()));
            t3.setText(String.valueOf(pi.getSeats()));
            t4.setText(pi.getAirport());
            t5.setText(pi.getExpdate());
            c1.setSelectedItem(pi.getMft());
            c2.setSelectedItem(pi.getAirliner());
            c3.setSelectedItem(String.valueOf(pi.getModel()));
            if(pi.isAvail()){
                cb1.setSelected(true);
            }else{
                cb2.setSelected(true);
            }
        }   
        else
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
        
        PlaneInfo pi= (PlaneInfo)tbl.getValueAt(selectedrow,0);
        ht.deletePlanes(pi);
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        if(cb2.isSelected()){
            cb1.setSelected(false);
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        if(cb1.isSelected()){
            cb2.setSelected(false);
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl.getSelectedRow();
        if(selectedrow >=0)
        {
            PlaneInfo p= (PlaneInfo)tbl.getValueAt(selectedrow,0);
            ht.deletePlanes((p));
            JOptionPane.showMessageDialog(null, "Deleted");
            populatetle();
            try{   
                BufferedWriter fw = new BufferedWriter(new FileWriter("file.txt"));
                for(PlaneInfo line : ht.getHistory()){
                    
                    String[] a = new String[10];
                    a[0]=String.valueOf(line.getId());
                    a[1]=String.valueOf(line.isAvail());
                    a[2]=line.getMft();
                    a[3]=String.valueOf(line.getMadeyear());
                    a[4]=String.valueOf(line.getSeats());
                    a[5]=String.valueOf(line.getModel());
                    a[6]=line.getAirliner();
                    a[7]=String.valueOf(line.getUpdate());
                    a[8]=line.getAirport();
                    a[9]=line.getExpdate();
                    String thisline=Arrays.toString(a);
                    fw.write(thisline.replace("[", "").replace("]", "").replace(", ",","));
                    fw.newLine();
                }     
                fw.close();    
            }catch(Exception e){System.out.println(e);}    
          System.out.println("Success...");
        }   
        else
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        
        int planeid= Integer.parseInt(t1.getText());
        boolean status = cb1.isSelected();
        String manufact = (String)c1.getSelectedItem();
        int yearmade = Integer.parseInt(t2.getText());
        int totalseats = Integer.parseInt(t3.getText());
        String airliner = (String)c2.getSelectedItem();
        int model = Integer.parseInt((String)c3.getSelectedItem());
        String airport= t4.getText();
        String expdate= t5.getText();
        Boolean e1=null;
        Boolean e2=null;
        if (yearmade<=1990 || yearmade>2017) {
            JOptionPane.showMessageDialog(null,"Invalid Year");
            e2=false;
            
        }else{e2=true;}
        
        Date date = null;
        try {
                DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                formatter.setLenient(false);
                date = formatter.parse(expdate);
            } catch (ParseException e) { 
                e.printStackTrace();
            }
        
        if(date == null){
            JOptionPane.showMessageDialog(null,"Invalid Date");
            e1= false;
        }else{
            e1=true;
        }
        if(e1&&e2){
        PlaneInfo p=ht.addPlanes();
        p.setId(planeid);
        p.setAvail(status);
        p.setMft(manufact);
        p.setMadeyear(yearmade);
        p.setAirliner(airliner);
        p.setSeats(totalseats);
        p.setAirport(airport);
        p.setModel(model);
        p.setExpdate(expdate);
        p.setUpdate(System.currentTimeMillis());
        
        try{   
                BufferedWriter fw = new BufferedWriter(new FileWriter("file.txt"));
                for(PlaneInfo line : ht.getHistory()){
                    
                    String[] a = new String[10];
                    a[0]=String.valueOf(line.getId());
                    a[1]=String.valueOf(line.isAvail());
                    a[2]=line.getMft();
                    a[3]=String.valueOf(line.getMadeyear());
                    a[4]=String.valueOf(line.getSeats());
                    a[5]=String.valueOf(line.getModel());
                    a[6]=line.getAirliner();
                    a[7]=String.valueOf(line.getUpdate());
                    a[8]=line.getAirport();
                    a[9]=line.getExpdate();
                    String thisline=Arrays.toString(a);
                    fw.write(thisline.replace("[", "").replace("]", "").replace(", ",","));
                    fw.newLine();
                }     
                fw.close();    
            }catch(Exception e){System.out.println(e);}    
          System.out.println("Success...");
          
        updatebtn.setEnabled(false);
        tbl.setEnabled(true);
        deletebtn.setEnabled(true);
        editbtn.setEnabled(true);
        
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        cb1.setSelected(false);
        cb2.setSelected(false);
        c1.setSelectedIndex(0);
        c2.setSelectedIndex(0);
        c3.setSelectedIndex(0);
        JOptionPane.showMessageDialog(null, "Saved");
        }
    }//GEN-LAST:event_updatebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTable tbl;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
