/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AgencyCustomerRole;

import Business.Data.Databank;
import Business.Enterprise.Agency;
import Business.Order.Quote;
import Business.Order.RealEstateOrder;
import Business.Organization.AgencyCustomerOrg;
import Business.Realestate.RealEstate;
import Business.Role.AgencyCustomer;
import Business.Rssystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruby
 */
public class ViewQuote extends javax.swing.JPanel {

    /**
     * Creates new form ViewQuote
     */
    private JPanel p;
    private Rssystem b;
    private Agency a;
    private AgencyCustomerOrg c;
    private UserAccount ua;
    private AgencyCustomer ac;
    
    ViewQuote(Rssystem b, JPanel p, Agency a, AgencyCustomerOrg c, UserAccount ua) {
        initComponents();
        this.p = p;
        this.b = b;
        this.a = a;
        this.c = c;
        this.ua = ua;
        this.ac = (AgencyCustomer)ua.getRole();
        populatetbl();
    }

    public void populatetbl(){
        DefaultTableModel dtm = (DefaultTableModel)tbl.getModel();
        dtm.setRowCount(0);
        for(Quote q : ac.getQuotelist()){
            Object row[] = new Object[6];
            row[0] = q;
            row[1] = q.getRealestate();
            row[2] = q.getRoom();
            row[3] = q.getDiscount();
            row[4] = q.getAgencycharge();
            row[5] = q.getUnitprice()*q.getDiscount()*q.getRoom().getRoomarea();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        orderbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(68, 75, 92));

        backbtn.setBackground(new java.awt.Color(128, 209, 196));
        backbtn.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Quote");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Quote ID", "RealEstate ID", "Room No.", "Discount", "Charges", "Final Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
            tbl.getColumnModel().getColumn(2).setResizable(false);
            tbl.getColumnModel().getColumn(3).setResizable(false);
            tbl.getColumnModel().getColumn(4).setResizable(false);
            tbl.getColumnModel().getColumn(5).setResizable(false);
        }

        orderbtn.setBackground(new java.awt.Color(128, 209, 196));
        orderbtn.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 24)); // NOI18N
        orderbtn.setForeground(new java.awt.Color(255, 255, 255));
        orderbtn.setText("Order");
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(576, 576, 576)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderbtn)
                .addContainerGap(394, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = tbl.getSelectedRow();
        if(selectedrow >= 0){
            RealEstate r = (RealEstate)tbl.getValueAt(selectedrow,1);
            Quote q = (Quote)tbl.getValueAt(selectedrow,0);
            if(!a.checkIfCustomerOrderExists(r, q.getRoom(), ua)){
                RealEstateOrder o = new RealEstateOrder(r,a,ua,q.getRoom(),q);
                q.getRoom().setStatus(false);
                o.setPrice(q.getTotalprice());
                DateFormat format = new SimpleDateFormat("yyyy/MM/dd HH:mm");
                Date date = new Date();
                o.setOrderid((int)(System.currentTimeMillis()%1000000000));
                o.setOrderdate(format.format(date));
                a.getOrderlist().add(o);
                JOptionPane.showMessageDialog(null, "Purchase Completed");
                Databank.getInstance().storeSystem(b);
            }else{
//                a.getOrderlist().remove(a.checkIfCustomerOrderExists(r, q.getRoom(), ua));
//                RealEstateOrder o = new RealEstateOrder(r,a,ua,q.getRoom());
//                q.getRoom().setStatus(false);
//                o.setPrice(q.getTotalprice());
//                DateFormat format = new SimpleDateFormat("yyyy/MM/dd HH:mm");
//                Date date = new Date();
//                o.setOrderid((int)(System.currentTimeMillis()%1000000000));
//                o.setOrderdate(format.format(date));
//                a.getOrderlist().add(o);
//                Databank.getInstance().storeSystem(b);
                JOptionPane.showMessageDialog(null, "Order Exists");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please Select Any Row");
        }
    }//GEN-LAST:event_orderbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderbtn;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
