/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeveloperBuyerWorkArea;

import Business.Data.Databank;
import Business.Enterprise.Developer;
import Business.Enterprise.Enterprise;
import Business.Order.LandOrder;

import Business.Organization.Organization;
import Business.Realestate.RealEstate;
import Business.Rssystem;
import Business.land.Land;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55303
 */
public class DeveloperBuyerOrder extends javax.swing.JPanel {

    /**
     * Creates new form DeveloperBuyerOrder
     */
    JPanel p;
    Rssystem b;
    Organization o;
    Developer e;
    public DeveloperBuyerOrder(JPanel p, Rssystem b, Organization o, Enterprise e) {
       initComponents();
       this.b = b;
       this.p = p;
       this.o = o;
       this.e = (Developer)e;
       populatetbl1();
       populatetbl2();
    }
  public void populatetbl1(){
        DefaultTableModel dtm= (DefaultTableModel)tbl1.getModel();
        dtm.setRowCount(0);
        for(Land re : e.getCity().getLandtobesold()){
            if(re.isStatus() == true){    
                Object row[]= new Object[4];
                row[0] = re;
                row[1] = re.getArea();
                row[2] = re.getUnitprice();
                row[3] = re.getAddress();
                dtm.addRow(row);
            }
        }
    }
    public void populatetbl2(){
        DefaultTableModel dtm= (DefaultTableModel)tbl2.getModel();
        dtm.setRowCount(0);
        for(LandOrder o : e.getOrderlist()){
                Object row[]= new Object[3];
                row[0] = o;
                row[1] = o.getLand();
                row[2] = o.getOrderdate();
                dtm.addRow(row);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        orderbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        detailbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(68, 75, 92));

        jLabel1.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Developer Buyer Work Area");

        backbtn.setBackground(new java.awt.Color(128, 209, 196));
        backbtn.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Logout");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Area", "Unit Price", "Address"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        orderbtn.setBackground(new java.awt.Color(128, 209, 196));
        orderbtn.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 24)); // NOI18N
        orderbtn.setForeground(new java.awt.Color(255, 255, 255));
        orderbtn.setText("Order");
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Land ID", "Order Date"
            }
        ));
        jScrollPane2.setViewportView(tbl2);

        deletebtn.setBackground(new java.awt.Color(128, 209, 196));
        deletebtn.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 24)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        detailbtn.setBackground(new java.awt.Color(128, 209, 196));
        detailbtn.setFont(new java.awt.Font("方正兰亭黑_GB18030", 1, 24)); // NOI18N
        detailbtn.setForeground(new java.awt.Color(255, 255, 255));
        detailbtn.setText("View Detail");
        detailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(orderbtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailbtn)
                        .addGap(49, 49, 49)
                        .addComponent(deletebtn))
                    .addComponent(jScrollPane2))
                .addContainerGap(552, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderbtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebtn)
                    .addComponent(detailbtn))
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        p.remove(this);
        CardLayout layout =(CardLayout) p.getLayout();
        layout.previous(p);
    }//GEN-LAST:event_backbtnActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl1.getSelectedRow();
        if(selectedrow >=0){
            Land r= (Land)tbl1.getValueAt(selectedrow,0);
            if(e.findLand(r.getAddress())==null){
                e.getLandlist().add(r);
                LandOrder o = new LandOrder(e, r.getLandowner(),r);
                DateFormat format = new SimpleDateFormat("dd/MM/yy HH:mm");
                Date date = new Date();
                o.setOrderid((int)(System.currentTimeMillis()%1000000000));
                o.setOrderdate(format.format(date));
                o.setPrice(r.getUnitprice());
                e.getOrderlist().add(o);
                r.getLandowner().getOrderlist().add(o);
                r.setStatus(false);
                Databank.getInstance().storeSystem(b);
                populatetbl2();
            }else{
                JOptionPane.showMessageDialog(null,"Land Has Been Ordered");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }
    }//GEN-LAST:event_orderbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl2.getSelectedRow();
        if(selectedrow >=0){
            Land r= (Land)tbl2.getValueAt(selectedrow,1);
            LandOrder o = (LandOrder)tbl2.getValueAt(selectedrow,0);
            e.getLandlist().remove(r);
            e.getOrderlist().remove(o);
            r.getLandowner().getOrderlist().remove(o);
            populatetbl2();
            Databank.getInstance().storeSystem(b);
        }else{
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void detailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= tbl2.getSelectedRow();
        if(selectedrow >=0){
            Land r= (Land)tbl2.getValueAt(selectedrow,1);
            LandOrder o = (LandOrder)tbl2.getValueAt(selectedrow,0);
            OrderDetail panel = new OrderDetail(r,o,p);
            p.add("Orderdetail",panel);
            CardLayout layout =(CardLayout) p.getLayout();
            layout.next(p);
            
            populatetbl2();
            Databank.getInstance().storeSystem(b);
        }else{
            JOptionPane.showMessageDialog(null,"Please Select Any Row");
        }
    }//GEN-LAST:event_detailbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton detailbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton orderbtn;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
}
